### ISSUE TITLE
Feature request - Use local files on the right side of the review diff split

### ISSUE THREAD

**Issue by pwntester** [pwntester/octo.nvim#103]
When possible, if CWD is in the PR repo and PR branch, use the local version of the file rather than downloading it from GH.

The idea is to be able to use LSP and other editor goodies on that buffer.

**Comment by pwntester** [comment]
Working on this, should be straightforward after last refactorings

**Comment by pwntester** [comment]
Implemeted in https://github.com/pwntester/octo.nvim/commit/6bc9d9ce4df93362719bd2eaa9e87aa2a39cd5a9

**Comment by dbriemann** [comment]
Sorry for necroing this but I have a related question. I cannot use lsp in the diff view because e.g. `pyright` cannot find the root folder of the project. I can use `gf` to go to the actual file and use lsp functions there but would it also be possible to use them directly in the diff view? Do I somehow have to open the pr differently or tell Octo that it should use the local file?
