### ISSUE TITLE
How to review a file that got added (with syntax highlighting)

### ISSUE THREAD

**Issue by entropitor** [pwntester/octo.nvim#161]
I want to try and review a file that got added. So I close the "old" file buffer as it's empty anyway. This way I get syntax highlighting for the added file. However, when I try to add a comment then, I get an error that it cannot find the window

Alternatively, is there a way to still get syntax highlighting but just have the signs for additions / changes?

**Comment by pwntester** [comment]
Hi 👋🏼 thanks for the report. 

> However, when I try to add a comment then, I get an error that it cannot find the window

We could use floats instead of the alternate window but I find moving around windows very non-intuitive when floats are involved. Otherwise, we need a new window to hold the thread/comment buffer. If we detect that the alternative window is not available we could create a new split but I think its better to not close the "old" one. 

What you can do is `:diffoff` on the "new" buffer to disable the diff mode and maybe make the "old" window smaller (you will still need it to show the comments)

Let me know if you have another idea on mind

 > Alternatively, is there a way to still get syntax highlighting but just have the signs for additions / changes?

You can use diff hl groups with no `guifg` color, you will get something like:

<img width="2125" alt="image" src="https://user-images.githubusercontent.com/125701/125045773-a654e180-e09d-11eb-9b6f-22855e679491.png">

eg: https://github.com/pwntester/nautilus.nvim/blob/main/lua/nautilus.lua#L168-L179

**Comment by entropitor** [comment]
Thanks!
