### ISSUE TITLE
Feature request: syntax highlighting for markdown in issue/PR descriptions/comments

### ISSUE THREAD

**Issue by farbodsz** [pwntester/octo.nvim#227]
Firstly, thanks for writing this plugin - it's so nice to have GitHub integrated within Neovim.

It would be great if the user's markdown syntax highlighting could be applied to the GitHub issue/PR descriptions and comments.

This would help highlight headings, code blocks, etc.

I'm happy to look into making a PR to add this in, if you agree! (I am a little busy over the next couple weeks though, so it may take a me longer than usual)

**Comment by pwntester** [comment]
Hi, that should be already implemented and documented in the [FAQ](https://github.com/pwntester/octo.nvim/blob/master/README.md#-faq), but since `OctoEditable` defaults to `NormalFloat`, I added some changes in https://github.com/pwntester/octo.nvim/commit/5e43e1f36755d67c31236a371831af7878b25884 to make sure the default highlight group does not use a  foreground color. Please check with latest version and let me know if it works as expected now

**Comment by farbodsz** [comment]
Thanks so much - your changes did help with the highlighting (highlighting headings, etc. that weren't being highlighted before!)

I use [`vim-markdown`](https://github.com/plasticboy/vim-markdown) to get syntax highlighting for code blocks too, but this doesn't seem to appear on the Octo issue preview. In the screenshot below I have a scratch markdown buffer (top) with the Octo issue (bottom) for comparison:

![screenshot_20211226_195711](https://user-images.githubusercontent.com/12140044/147418766-f387eafd-ae46-42d9-a5a6-18e43ced0b6f.png)

Not sure whether this is an issue for `vim-markdown` or `octo.nvim`, or just something I need to configure with my highlight groups, so if you could point me in the right direction that would be much appreciated!

**Comment by pwntester** [comment]
Can you try clearing the `OctoEditable` hl group?

**Comment by farbodsz** [comment]
Clearing the `OctoEditable` highlight group removes the background but doesn't affect my foreground colours:

![screenshot_20211227_014830](https://user-images.githubusercontent.com/12140044/147426259-6733803b-051e-42a1-af73-9ae7febbaf83.png)

_Octo preview (left); and same content in a markdown scratch buffer (right)_

**Comment by farbodsz** [comment]
I can run `:TSHighlightCapturesUnderCursor` (from `nvim-treesitter`), and that gives the following results:

![screenshot_20211227_015100](https://user-images.githubusercontent.com/12140044/147426410-d214db3f-81c6-4186-bb25-4fbcb41fe917.png)

**Comment by pwntester** [comment]
Octo uses a custom `octo` filetype and syntax. Syntax is defined in https://github.com/pwntester/octo.nvim/blob/ea8aef7e0c3ae67fa46a46ee58623be3a201c968/after/syntax/octo.vim and it embeds markdown syntax. Perhaps vim-markdown defines additional syntax that is not imported by `octo` syntax. I dont use vim-markdown. Can you check if any addtional syntax files could be imported in the octo one?

A custom octo treesiter parser would be awesome but not sure if feasable since most octo text is virtual text

**Comment by pwntester** [comment]
Hi @farbodsz 

Just tried enabling the markdown treesitter for `octo` and it seems to work as you expect:

![image](https://user-images.githubusercontent.com/125701/147511514-a69dfd92-4ad2-4cac-912b-04ef5adb25a6.png)

You just need to add these lines to your treesitter config:

```lua
  local parser_config = require("nvim-treesitter.parsers").get_parser_configs()
  parser_config.markdown.used_by = "octo"

```

**Comment by farbodsz** [comment]
Ah this is perfect, thank you - I didn't realise this was possible!
