### ISSUE TITLE
bug:🐛 Freezes on showing diff for new files in PR review

### ISSUE THREAD

**Issue by GustavEikaas** [pwntester/octo.nvim#603]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)
When reviewing a pr in octo it freezes upon entering new files(A). 

### How to reproduce it (as minimally and precisely as possible)

1. Start a PR review
2. Cycle through files until you reach a new file
3. It freezes

### Tell us your environment
Windows 10
NVIM v0.10.1
Octo 50c6225

**Comment by pwntester** [comment]
Hi @GustavEikaas I cant reproduce the issue on my end. When you open the diff for an added file, the cursor is placed in the left side of the diff and since there are no lines in that buffer you cannot move the cursor. But moving to the right window of the diff, I can move through the buffer.

Does this issue happen in a public PR I can review?

**Comment by GustavEikaas** [comment]
I did some testing/digging and it seems to specifically happen for .cs files in my case, so im fairly confident that it is an issue with my neovim config and not the plugin itself. Ill keep digging

**Comment by GustavEikaas** [comment]
Yeah, ill close this issue. It is something in my neovim config causing the freeze.
